name: Release Pipeline

on:
  push:
    tags:
      - 'v*'

env:
  OUTPUT_FOLDER: "output"
  FILENAME: "library"

jobs:
  pack-library:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository for deployment
        uses: actions/checkout@v7

      - name: Checkout core_types-format repository
        uses: actions/checkout@v7
        with:
          repository: 0x007E/core_types-format
          path: core_types-format
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout core_types-return repository
        uses: actions/checkout@v7
        with:
          repository: 0x007E/core_types-return
          path: core_types-return
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout hal-common repository
        uses: actions/checkout@v7
        with:
          repository: 0x007E/hal-common
          path: hal-common
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Checkout hal-avr0-twi repository
        uses: actions/checkout@v7
        with:
          repository: 0x007E/hal-avr0-twi
          path: hal-avr0-twi
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout utils-macros repository
        uses: actions/checkout@v7
        with:
          repository: 0x007E/utils-macros
          path: utils-macros
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout utils-systick repository
        uses: actions/checkout@v7
        with:
          repository: 0x007E/utils-systick
          path: utils-systick
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout utils-time repository
        uses: actions/checkout@v7
        with:
          repository: 0x007E/utils-time
          path: utils-time
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare library package
        run: |
          mkdir -p ./${{ env.OUTPUT_FOLDER }}/core_types/format
          cp -r ./core_types-format/time.h ./${{ env.OUTPUT_FOLDER }}/core_types/format/

          mkdir -p ./${{ env.OUTPUT_FOLDER }}/core_types/return
          cp -r ./core_types-return/status.h ./${{ env.OUTPUT_FOLDER }}/core_types/return/

          mkdir -p ./${{ env.OUTPUT_FOLDER }}/hal/common
          mkdir -p ./${{ env.OUTPUT_FOLDER }}/hal/common/defines
          mkdir -p ./${{ env.OUTPUT_FOLDER }}/hal/common/enums
          cp -r ./hal-common/defines/TWI_defines.h ./${{ env.OUTPUT_FOLDER }}/hal/common/defines/
          cp -r ./hal-common/enums/TWI_enums.h ./${{ env.OUTPUT_FOLDER }}/hal/common/enums/

          mkdir -p ./${{ env.OUTPUT_FOLDER }}/hal/avr0/twi
          cp -r ./hal-avr0-twi/twi.c ./${{ env.OUTPUT_FOLDER }}/hal/avr0/twi/
          cp -r ./hal-avr0-twi/twi.h ./${{ env.OUTPUT_FOLDER }}/hal/avr0/twi/

          mkdir -p ./${{ env.OUTPUT_FOLDER }}/utils/macros
          cp -r ./utils-macros/stringify.h ./${{ env.OUTPUT_FOLDER }}/utils/macros/

          mkdir -p ./${{ env.OUTPUT_FOLDER }}/utils/systick
          cp -r ./utils-systick/systick.c ./${{ env.OUTPUT_FOLDER }}/utils/systick/
          cp -r ./utils-systick/systick.h ./${{ env.OUTPUT_FOLDER }}/utils/systick/

          mkdir -p ./${{ env.OUTPUT_FOLDER }}/utils/time
          cp -r ./utils-time/validate.c ./${{ env.OUTPUT_FOLDER }}/utils/time/
          cp -r ./utils-time/validate.h ./${{ env.OUTPUT_FOLDER }}/utils/time/
          
          mkdir -p ./${{ env.OUTPUT_FOLDER }}/drivers/rtc/mcp7940
          cp -r ./mcp7940.c ./${{ env.OUTPUT_FOLDER }}/drivers/rtc/mcp7940/
          cp -r ./mcp7940.h ./${{ env.OUTPUT_FOLDER }}/drivers/rtc/mcp7940/

          cp -r ./LICENSE ./${{ env.OUTPUT_FOLDER }}/

      - name: Upload library package
        uses: actions/upload-artifact@v7
        with:
            name: library-package
            path: ./${{ env.OUTPUT_FOLDER }}
            retention-days: 1

  create-release:
    needs: [pack-library]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_REPO: ${{ github.repository }}
    steps:
      - name: Create Release
        run: |
          gh release create "${{ github.ref_name }}" \
            --title "Release ${{ github.ref_name }}" \
            --notes "Release ${{ github.ref_name }}"

      - name: Download Library Artifacts
        uses: actions/download-artifact@v8
        with:
            name: library-package
            path: ./artifact/${{ env.FILENAME }}
    
      - name: Display structure
        run: ls -R ./artifact/${{ env.FILENAME }}
    
      - name: Create Compressed File
        run: |
            cd ./artifact
            tar -czvf ./${{ env.FILENAME }}.tar.gz ./${{ env.FILENAME }}
            zip -r ./${{ env.FILENAME }}.zip ./${{ env.FILENAME }}
            cd ..

      - name: Upload files
        run: |
          gh release upload ${{ github.ref_name }} \
            ./artifact/${{ env.FILENAME }}.tar.gz \
            ./artifact/${{ env.FILENAME }}.zip
      
      - name: Rollback release on failure
        if: failure()
        run: |
          gh release delete "${{ github.ref_name }}" -y --cleanup-tag
          git push --delete origin "${{ github.ref_name }}" || true